# Generated by Django 2.1.15 on 2020-03-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanDiego_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=20, null=True)),
                ('street_name', models.CharField(max_length=30, null=True)),
                ('street_sfx', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=10, null=True)),
                ('zip', models.CharField(max_length=20, null=True)),
                ('apn', models.CharField(max_length=20, null=True)),
                ('parcel_id', models.CharField(max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SanDiego_Affordable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=50)),
                ('data', models.TextField(default='{}')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SanDiego_Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(max_length=10)),
                ('lot_area', models.CharField(max_length=20)),
                ('lot_length', models.CharField(max_length=20, null=True)),
                ('geometry', models.TextField()),
                ('apn', models.CharField(max_length=20, null=True)),
                ('owner1', models.CharField(max_length=100, null=True)),
                ('owner2', models.CharField(max_length=100, null=True)),
                ('owner3', models.CharField(max_length=100, null=True)),
                ('owner_address_1', models.CharField(max_length=100, null=True)),
                ('owner_address_2', models.CharField(max_length=100, null=True)),
                ('owner_address_3', models.CharField(max_length=100, null=True)),
                ('owner_address_4', models.CharField(max_length=100, null=True)),
                ('owner_zip', models.CharField(max_length=20, null=True)),
                ('number', models.CharField(max_length=10, null=True)),
                ('street_name', models.CharField(max_length=20, null=True)),
                ('street_sfx', models.CharField(max_length=10, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('zip', models.CharField(max_length=20, null=True)),
                ('legal_desc', models.CharField(max_length=100, null=True)),
                ('asr_land', models.CharField(max_length=20, null=True)),
                ('asr_impr', models.CharField(max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SanDiego_TransitArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('geometry', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SanDiego_Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('geometry', models.TextField()),
                ('imp_date', models.CharField(max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SanDiego_ZoneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('parent', models.CharField(max_length=50, null=True)),
                ('development_regs', models.TextField()),
                ('use_regs', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
