# Generated by Django 2.1.15 on 2020-02-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=20)),
                ('street_sfx', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=10)),
                ('apn', models.CharField(max_length=20)),
                ('parcel_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(max_length=10)),
                ('apn', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=20)),
                ('street_sfx', models.CharField(max_length=10)),
                ('zip', models.CharField(max_length=10)),
                ('lot_area', models.CharField(max_length=20)),
                ('geometry', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('imp_date', models.CharField(max_length=10)),
                ('geometry', models.TextField()),
            ],
        ),
    ]
