# Generated by Django 2.1.15 on 2020-03-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dig', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandiego_zoneinfo',
            name='parent',
        ),
        migrations.AlterField(
            model_name='sandiego_zoneinfo',
            name='development_regs',
            field=models.TextField(default='{"parent": null, "rule_dict": {}, "footnotes_dict": {}}'),
        ),
        migrations.AlterField(
            model_name='sandiego_zoneinfo',
            name='use_regs',
            field=models.TextField(default='{"parent": null, "rule_dict": {}, "footnotes_dict": {}}'),
        ),
    ]
