# Generated by Django 2.1.15 on 2020-02-27 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dig', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='SanDiego_Address',
        ),
        migrations.RenameModel(
            old_name='Parcel',
            new_name='SanDiego_Parcel',
        ),
        migrations.RenameModel(
            old_name='Zone',
            new_name='SanDiego_Zone',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
