# Generated by Django 2.2.8 on 2020-03-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dig', '0002_auto_20200303_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanJose_Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(max_length=10)),
                ('lot_area', models.CharField(max_length=20)),
                ('lot_length', models.CharField(max_length=20, null=True)),
                ('geometry', models.TextField()),
                ('apn', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SanJose_ZoneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('development_regs', models.TextField(default='{"parent": null, "rule_dict": {}, "footnotes_dict": {}}')),
                ('use_regs', models.TextField(default='{"parent": null, "rule_dict": {}, "footnotes_dict": {}}')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
