# Generated by Django 2.2.8 on 2020-03-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dig', '0003_sanjose_parcel_sanjose_zoneinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanJose_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=20, null=True)),
                ('street_name', models.CharField(max_length=30, null=True)),
                ('street_sfx', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=10, null=True)),
                ('zip', models.CharField(max_length=20, null=True)),
                ('apn', models.CharField(max_length=20, null=True)),
                ('parcel_id', models.CharField(max_length=10, null=True)),
                ('full_address', models.CharField(max_length=100, null=True)),
                ('number_pre', models.CharField(max_length=30, null=True)),
                ('number_sfx', models.CharField(max_length=30, null=True)),
                ('room', models.CharField(max_length=20, null=True)),
                ('seat', models.CharField(max_length=20, null=True)),
                ('unit_full', models.CharField(max_length=20, null=True)),
                ('jurisdiction', models.CharField(max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
