# Generated by Django 2.1.15 on 2020-02-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dig', '0003_auto_20200227_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandiego_address',
            name='state',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='street_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='street_sfx',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='zip',
            field=models.CharField(max_length=20),
        ),
    ]
