# Generated by Django 2.1.15 on 2020-02-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dig', '0004_auto_20200227_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandiego_address',
            name='apn',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='city',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='number',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='parcel_id',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='street_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='street_sfx',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='unit',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='zip',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
