# Generated by Django 2.2.8 on 2020-03-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dig', '0004_sanjose_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanjose_address',
            name='street_name_pre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sanjose_address',
            name='street_name_pre_sep',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
