# Generated by Django 2.1.15 on 2020-02-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dig', '0005_auto_20200227_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandiego_address',
            name='apn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='parcel_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='state',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='street_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='street_sfx',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='unit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='zip',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sandiego_parcel',
            name='apn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sandiego_parcel',
            name='street_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sandiego_parcel',
            name='street_sfx',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sandiego_parcel',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sandiego_zone',
            name='imp_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
