# Generated by Django 2.2.8 on 2020-03-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dig', '0005_auto_20200316_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanJose_Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('geometry', models.TextField()),
                ('color_code', models.CharField(max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='sanjose_parcel',
            name='apn',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
