# Generated by Django 2.1.15 on 2020-02-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dig', '0006_auto_20200227_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandiego_parcel',
            name='asr_impr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sandiego_parcel',
            name='asr_land',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sandiego_parcel',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sandiego_parcel',
            name='legal_desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sandiego_parcel',
            name='lot_length',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sandiego_parcel',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sandiego_parcel',
            name='owner1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sandiego_parcel',
            name='owner2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sandiego_parcel',
            name='owner3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sandiego_parcel',
            name='owner_address_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sandiego_parcel',
            name='owner_address_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sandiego_parcel',
            name='owner_address_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sandiego_parcel',
            name='owner_address_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sandiego_parcel',
            name='owner_zip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='state',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sandiego_address',
            name='zip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sandiego_parcel',
            name='zip',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
