# Generated by Django 2.1.15 on 2020-02-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dig', '0007_auto_20200229_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanDiego_TransitArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('geometry', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='sandiego_zone',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
